### ISSUE TITLE
Scooby doo classic creep capers minor graphics glitch.

### ISSUE THREAD

**Issue by jmc92** [skylersaleh/SkyEmu#60] opened 2022-07-14 09:33 UTC
Dr Jekyll's head keeps flickering in visibility.
![sky emu scooby](https://user-images.githubusercontent.com/23234604/178958232-8d29efcc-818b-4dc3-a841-ce9dba997d14.jpg)

Updated correct screenshot. Other emulators have this too, might be glitched on hardware as well.
This persists, even while using the official bios.

**Comment by skylersaleh** [comment] 2022-07-14 15:17
Adding the help wanted tag here. Is there someone who can verify whether this bug occurs on HW?

**Comment by jmc92** [comment] 2022-07-14 19:08
> Adding the help wanted tag here. Is there someone who can verify whether this bug occurs on HW?

There is a chance I can do so next week if I remember. My cartridge of this game resides with family members now.

**Comment by benderscruffy** [comment] 2022-07-16 10:06
it happens on hardware aswell
not a bug

**Comment by skylersaleh** [comment] 2022-07-16 23:50
Thanks @benderscruffy for testing this out. I'll close this issue.

**Closed by skylersaleh** 2022-07-16 23:50 UTC
Labels: help wanted, gb
