### ISSUE TITLE
Controller: d-pad bindings aren't working.

### ISSUE THREAD

**Issue by RetroEdit** [skylersaleh/SkyEmu#307] opened 2023-07-29 01:39 UTC
The rest of the gamepad bindings work for my controller, but the d-pad doesn't, probably because the d-pad on my controller is classified as an analog stick. The controller gets recognized as a `USB, 2-axis 8-button gamepad`.

My controller is an iBuffalo Classic USB Gamepad, model BSGP815GY.

I'm running SkyEmu v2 on Windows 11.

**Comment by RetroEdit** [comment] 2023-07-29 02:06
I tested on https://web.skyemu.app/ and it appears to work. I guess this has probably been addressed in the intervening time since v2.

I guess I might download and build it, since I don't really fancy using the web build in particular.

**Comment by skylersaleh** [comment] 2023-07-29 02:09
There is some CI builds of dev here. 

https://github.com/skylersaleh/SkyEmu/pull/143

**Comment by RetroEdit** [comment] 2023-07-29 04:20
Whoops, I guess this *is* actually still present in the latest Windows build at 483f1da : https://github.com/skylersaleh/SkyEmu/actions/runs/5696087338

**Comment by skylersaleh** [comment] 2023-07-31 05:57
Closing, since the fix mainlined was confirmed to work over discord.

**Closed by skylersaleh** 2023-07-31 05:57 UTC
